import type { Dict } from "@/lib/dict/ja";

export const en: Dict = {
  meta: {
    title: "Ryokuhoen Co., Ltd. | Kyoto Higashiyama — Restaurants & Confectionery",
    titleShort: "Ryokuhoen Co., Ltd.",
    titleTemplate: "%s | Ryokuhoen Co., Ltd.",
    description:
      "Ryokuhoen Co., Ltd. is based at the foot of Yasaka Pagoda in Higashiyama, Kyoto. Through our restaurants, our own confectionery workshop and our online store, we bring the food culture of Kyoto to the table.",
    ogAlt: "Yasaka Pagoda through night cherry blossoms, Higashiyama, Kyoto",
    factoryTitle: "Tsuburano Sweets Factory",
    factoryDescription:
      "Tsuburano Sweets Factory is the confectionery workshop of Ryokuhoen Co., Ltd. We plan, develop and produce original sweets, with private-label production from small lots.",
  },
  nav: {
    business: "Business",
    factory: "Workshop",
    company: "Company",
    contact: "Contact",
    menu: "Menu",
    close: "Close",
    home: "Home",
    language: "Language",
    skip: "Skip to content",
    newTab: " (opens in a new tab)",
  },
  hero: {
    ariaLabel: "From Higashiyama, Kyoto",
    kicker: "KYOTO / FOOD CULTURE",
    display: ["The food of Kyoto —", "prepared, opened,", "and delivered."],
    ctaBusiness: "Our business",
    ctaContact: "Contact us",
    scroll: "Scroll",
    scenes: [
      { alt: "Yasaka Pagoda seen through night cherry blossoms, Higashiyama, Kyoto", kicker: "Higashiyama" },
      {
        alt: "Entrance with a noren curtain, moss garden and stepping stones",
        kicker: "Entrance",
        title: ["Through the curtain,", "into the garden."],
        caption: "A step inward from the Kiyomizu approach.",
      },
      {
        alt: "Looking up at wooden eaves and young maple leaves",
        kicker: "Seasons",
        title: ["Color of the season,", "under wooden eaves."],
        caption: "The house and its garden mirror the season.",
      },
      {
        alt: "Hassun course served on vermilion lacquerware",
        kicker: "Hassun",
        title: ["A season,", "on a single plate."],
        caption: "Hassun — the season reflected in its vessel.",
      },
    ],
  },
  policy: {
    kicker: "Our Policy",
    h2: ["From Kyoto,", "sharing its food culture."],
    body:
      "At the foot of Yasaka Pagoda in Higashiyama stands our head restaurant, Tsuburano Kyoto, in a hundred-year-old sukiya-style house. From here we add new value to traditional flavors: a coffee house roasting its own beans in Gojo, and a confectionery workshop near Kansai International Airport that produces and supplies sweets.",
    alt: "The sloping lane to Yasaka Pagoda and the exterior of Tsuburano Kyoto",
    caption: "The lane to Yasaka Pagoda, Higashiyama — Tsuburano Kyoto",
  },
  sweets: {
    index: "Business",
    kicker: "Sweets",
    h2: "Confectionery",
    lead: ["True to the ingredients,", "baked with care."],
    body:
      "Our chef pâtissier, trained at renowned patisseries, leads production in our own workshop — from baked goods to delicate fresh confectionery. We supply original sweets to JR Kyoto Isetan and a wide range of department stores and supermarkets, and we take on private-label production and product development from small lots.",
    cta: "See the workshop",
    alt: "Tsuburano dorayaki: matcha and chocolate batter filled with warabi mochi and cream, tea leaves on slate",
    caption: ["Tsuburano dorayaki", "matcha and chocolate,", "filled with warabi mochi and cream"],
    insetAlt: "Deck oven in our workshop",
    insetCaption: "Our workshop — deck oven",
  },
  stores: {
    index: "Business",
    kicker: "Stores",
    h2: "Restaurants",
    intro:
      "Tsuburano Kyoto, a restaurant and sweets house in Higashiyama; Tsuburano Shinjuku Gyoen, inside the Shinjuku Gyoen National Garden in Tokyo; and Umamachi Coffee, serving house-roasted coffee and sweets. Please visit us when you are in Kyoto.",
    items: [
      {
        name: "Tsuburano Kyoto",
        desc: "Restaurant and sweets house",
        addr: "368-1-8 Yasakakamimachi, Higashiyama-ku, Kyoto",
        alt: "Tsuburano makunouchi bento: rolled omelet, grilled dishes and simmered vegetables",
      },
      {
        name: "Tsuburano Shinjuku Gyoen",
        desc: "Opened March 2022",
        addr: "11 Naitomachi, Shinjuku-ku, Tokyo (inside Shinjuku Gyoen)",
        alt: "Interior of Tsuburano Shinjuku Gyoen with a wooden counter and white noren",
      },
      {
        name: "Umamachi Coffee",
        desc: "House-roasted coffee and sweets",
        addr: "",
        alt: "Exterior of Umamachi Coffee with red pillars and the UMAMACHI COFFEE sign",
      },
    ],
  },
  shop: {
    index: "Business",
    kicker: "Online Store",
    h2: "Online Store",
    lead: ["From our workshop,", "to your table."],
    body:
      "Tsuburano sweets are shipped directly from our own workshop. We also offer original blends of coffee, slowly roasted on a GIESEN roaster from fair-trade green beans sourced around the world.",
    alt: "Tsuburano Kyoto Voyage baked sweets: colorful cookies and small confections on a white plate",
    caption: "Tsuburano “Kyoto Voyage” baked sweets",
  },
  company: {
    kicker: "Company",
    h2: "Company",
    nameLabel: "Name",
    capitalLabel: "Capital",
    capitalValue: "10 million yen",
    trustTitle: "What we do",
    areas: [
      "Restaurant operation",
      "Dashimaki sandwiches wholesale to JR Kyoto Isetan",
      "Sweets for airline business class",
      "Private-label production for department stores and hotels",
      "Tea from contracted farms in Uji",
      "House-roasted coffee beans wholesale",
    ],
    alt: "Matcha in a black bowl with two sweets on washi paper",
  },
  contact: {
    kicker: "Contact",
    h2: "Contact",
    body:
      "For business enquiries, private-label production and product development, or questions about our restaurants, please write to us here.",
    addressLabel: "Address",
    telLabel: "Phone",
    emailLabel: "Email",
    addressLines: ["368-1 Yasakakamimachi, Higashiyama-ku,", "Kyoto 605-0827, Japan"],
    form: {
      name: "Name",
      email: "Email address",
      message: "Your message",
      submit: "Send",
      sending: "Sending…",
      note: "The form is not live yet. Pressing send will open an email instead.",
      done: "Thank you. We have received your message and will be in touch.",
      failed: "The message could not be sent. Please email us instead.",
      preparing: "The form is not live yet. Please email us instead.",
      mailLink: "Send your message by email",
      mailSubject: "Enquiry from the website",
      mailName: "Name",
      mailEmail: "Email",
    },
  },
  footer: {
    siteLabel: "Site",
    brandsLabel: "Brands",
    policy: "Policy",
    business: "Business",
  },
  factory: {
    kicker: "The workshop of Ryokuhoen",
    title: ["Tsuburano", "Sweets Factory"],
    lead: ["Near Kansai International Airport,", "the workshop of Ryokuhoen Co., Ltd."],
    heroAlt: "Matcha and chestnut terrines on vermilion lacquerware with a gift box",
    introKicker: "Original Sweets",
    introH2: ["Your own sweets,", "from concept to production."],
    introBody:
      "Our chef pâtissier, trained at renowned patisseries, creates delicate confectionery. We handle the planning, development and production of your original products from beginning to end. Please feel free to talk to us.",
    galleryLabel: "Photographs of the workshop and its products",
    gallery: [
      { alt: "Colorful patterned sweets arranged on black slate", caption: "" },
      { alt: "Deck oven in the workshop", caption: "Deck oven" },
      { alt: "Proofing cabinet in the workshop", caption: "Proofer" },
      { alt: "Tsuburano gift boxes in black and white", caption: "" },
    ],
    strengthKicker: "Quality",
    strengthH2: "How we produce",
    strengths: [
      {
        t: "Concept to production",
        d: "We plan, develop and produce your original products entirely in our own workshop.",
      },
      { t: "Small lots welcome", d: "We develop and produce original products from small lots." },
      {
        t: "Baked and fresh confectionery",
        d: "Our chef pâtissier, trained at renowned patisseries, makes everything from baked goods to delicate fresh sweets.",
      },
      {
        t: "Rigorous hygiene management",
        d: "From the choice of ingredients to every step of production, we work under strict management.",
      },
    ],
    destKicker: "Partners",
    destH2: "Who we supply",
    destBody:
      "Starting with JR Kyoto Isetan, we deliver original sweets to customers such as the following.",
    destinations: ["Department stores", "Hotels", "Airline business class", "Supermarkets"],
    destAlt: "A gift box with six patterned sweets",
    contactKicker: "Contact",
    contactH2: "Talk to us about production",
    contactForm: "Contact us through the form",
    contactHome: "Back to Ryokuhoen home",
  },
};
