import type { Dict } from "@/lib/dict/ja";

export const es: Dict = {
  meta: {
    title: "Ryokuhoen Co., Ltd. | Kioto, Higashiyama — restaurantes y repostería",
    titleShort: "Ryokuhoen Co., Ltd.",
    titleTemplate: "%s | Ryokuhoen Co., Ltd.",
    description:
      "Ryokuhoen Co., Ltd. tiene su casa principal al pie de la pagoda Yasaka, en Higashiyama, Kioto. A través de nuestros restaurantes, nuestro obrador de repostería y nuestra tienda en línea, llevamos la cocina de Kioto a la mesa.",
    ogAlt: "La pagoda Yasaka entre cerezos en flor de noche (Higashiyama, Kioto)",
    factoryTitle: "Tsuburano Sweets Factory",
    factoryDescription:
      "Tsuburano Sweets Factory es el obrador de Ryokuhoen Co., Ltd. Diseñamos, desarrollamos y elaboramos dulces originales, con producción para terceros desde lotes pequeños.",
  },
  nav: {
    business: "Actividad",
    factory: "Obrador",
    company: "Empresa",
    contact: "Contacto",
    menu: "Menu",
    close: "Close",
    home: "Inicio",
    language: "Idioma",
    skip: "Ir al contenido",
    newTab: " (se abre en una pestaña nueva)",
  },
  hero: {
    ariaLabel: "Desde Higashiyama, Kioto",
    kicker: "KYOTO / FOOD CULTURE",
    display: ["La cocina de Kioto:", "dispuesta, abierta", "y compartida."],
    ctaBusiness: "Nuestra actividad",
    ctaContact: "Contacto",
    scroll: "Scroll",
    scenes: [
      { alt: "La pagoda Yasaka entre cerezos en flor de noche (Higashiyama, Kioto)", kicker: "Higashiyama" },
      {
        alt: "Entrada con cortina noren, jardín de musgo y pasaderas de piedra",
        kicker: "Entrance",
        title: ["Tras la cortina,", "el jardín interior."],
        caption: "Un paso adentro desde el camino de Kiyomizu.",
      },
      {
        alt: "Alero de madera y hojas tiernas de arce vistos desde abajo",
        kicker: "Seasons",
        title: ["Bajo el alero,", "el color del tiempo."],
        caption: "La casa y su jardín reflejan la estación.",
      },
      {
        alt: "Plato hassun servido en laca bermellón",
        kicker: "Hassun",
        title: ["La estación,", "en un solo plato."],
        caption: "Hassun: la estación reflejada en la vajilla.",
      },
    ],
  },
  policy: {
    kicker: "Our Policy",
    h2: ["Desde Kioto,", "su cultura gastronómica."],
    body:
      "Al pie de la pagoda Yasaka, en Higashiyama, se encuentra nuestra casa principal, Tsuburano Kioto, en un edificio de estilo sukiya de cien años. Desde aquí añadimos valor nuevo a los sabores de siempre: una cafetería con tueste propio en Gojo y un obrador cerca del aeropuerto de Kansai que elabora y distribuye repostería.",
    alt: "La cuesta que sube hacia la pagoda Yasaka y la fachada de Tsuburano Kioto",
    caption: "La cuesta hacia la pagoda Yasaka, Higashiyama — Tsuburano Kioto",
  },
  sweets: {
    index: "Business",
    kicker: "Sweets",
    h2: "Repostería",
    lead: ["Fieles al ingrediente,", "horneados con cuidado."],
    body:
      "Nuestro chef pastelero, formado en reconocidas pastelerías, dirige la elaboración en nuestro propio obrador: desde dulces horneados hasta delicados dulces frescos. Servimos dulces originales a JR Kyoto Isetan y a grandes almacenes y supermercados, y asumimos producción para terceros y desarrollo de producto desde lotes pequeños.",
    cta: "Ver el obrador",
    alt: "Dorayaki de Tsuburano: masa de matcha y chocolate rellena de warabi mochi y crema, con hojas de té sobre pizarra",
    caption: ["Dorayaki de Tsuburano", "matcha y chocolate,", "con warabi mochi y crema"],
    insetAlt: "Horno de solera de nuestro obrador",
    insetCaption: "Nuestro obrador — horno de solera",
  },
  stores: {
    index: "Business",
    kicker: "Stores",
    h2: "Restaurantes",
    intro:
      "Tsuburano Kioto, casa de comidas y dulces en Higashiyama; Tsuburano Shinjuku Gyoen, dentro del jardín nacional Shinjuku Gyoen de Tokio; y Umamachi Coffee, con café de tueste propio y repostería. Le esperamos cuando visite Kioto.",
    items: [
      {
        name: "Tsuburano Kioto",
        desc: "Casa de comidas y dulces",
        addr: "368-1-8 Yasakakamimachi, Higashiyama-ku, Kioto",
        alt: "Bento makunouchi de Tsuburano: tortilla dashimaki, platos a la parrilla y verduras guisadas",
      },
      {
        name: "Tsuburano Shinjuku Gyoen",
        desc: "Abierto en marzo de 2022",
        addr: "11 Naitomachi, Shinjuku-ku, Tokio (dentro de Shinjuku Gyoen)",
        alt: "Interior de Tsuburano Shinjuku Gyoen con barra de madera y cortina noren blanca",
      },
      {
        name: "Umamachi Coffee",
        desc: "Café de tueste propio y repostería",
        addr: "",
        alt: "Fachada de Umamachi Coffee con pilares rojos y el rótulo UMAMACHI COFFEE",
      },
    ],
  },
  shop: {
    index: "Business",
    kicker: "Online Store",
    h2: "Tienda en línea",
    lead: ["Del obrador,", "a su mesa."],
    body:
      "Enviamos los dulces de Tsuburano directamente desde nuestro obrador. También ofrecemos mezclas propias de café, tostado lentamente en un tostador GIESEN a partir de granos verdes de comercio justo seleccionados en todo el mundo.",
    alt: "Dulces horneados «Kyoto Voyage» de Tsuburano: galletas y pequeñas piezas de colores en un plato blanco",
    caption: "Dulces horneados «Kyoto Voyage» de Tsuburano",
  },
  company: {
    kicker: "Company",
    h2: "La empresa",
    nameLabel: "Razón social",
    capitalLabel: "Capital social",
    trustTitle: "A qué nos dedicamos",
    areas: [
      "Explotación de restaurantes",
      "Sándwiches de tortilla dashimaki para JR Kyoto Isetan",
      "Dulces para clase business de aerolíneas",
      "Producción para grandes almacenes y hoteles",
      "Té de fincas concertadas en Uji",
      "Café de tueste propio al por mayor",
    ],
    alt: "Matcha en cuenco negro y dos dulces sobre papel washi",
  },
  contact: {
    kicker: "Contact",
    h2: "Contacto",
    body:
      "Para consultas comerciales, producción para terceros y desarrollo de producto, o preguntas sobre nuestros restaurantes, escríbanos aquí.",
    addressLabel: "Dirección",
    telLabel: "Teléfono",
    emailLabel: "Correo",
    addressLines: ["368-1 Yasakakamimachi, Higashiyama-ku,", "Kioto 605-0827, Japón"],
    form: {
      name: "Nombre",
      email: "Correo electrónico",
      message: "Su consulta",
      submit: "Enviar",
      sending: "Enviando…",
      note: "El formulario aún no está activo. Al pulsar enviar se abrirá un correo electrónico.",
      done: "Hemos recibido su consulta. La revisaremos y nos pondremos en contacto con usted.",
      failed: "No se pudo enviar el mensaje. Por favor, escríbanos por correo electrónico.",
      preparing: "El envío del formulario aún no está activo. Por favor, escríbanos por correo electrónico.",
      mailLink: "Enviar el texto por correo electrónico",
      mailSubject: "Consulta desde el sitio web",
      mailName: "Nombre",
      mailEmail: "Correo",
    },
  },
  footer: {
    siteLabel: "Site",
    brandsLabel: "Brands",
    policy: "Filosofía",
    business: "Actividad",
  },
  factory: {
    kicker: "El obrador de Ryokuhoen",
    title: ["Tsuburano", "Sweets Factory"],
    lead: ["Cerca del aeropuerto de Kansai,", "el obrador de Ryokuhoen Co., Ltd."],
    heroAlt: "Terrinas de matcha y castaña sobre laca bermellón, con su caja de regalo",
    introKicker: "Original Sweets",
    introH2: ["Su producto original,", "del concepto a la producción."],
    introBody:
      "Nuestro chef pastelero, formado en reconocidas pastelerías, elabora dulces delicados. Nos ocupamos del diseño, el desarrollo y la producción de su producto original de principio a fin. Consúltenos sin compromiso.",
    galleryLabel: "Fotografías del obrador y sus productos",
    gallery: [
      { alt: "Dulces con dibujos de colores dispuestos sobre pizarra negra", caption: "" },
      { alt: "Horno de solera del obrador", caption: "Horno de solera" },
      { alt: "Cámara de fermentación del obrador", caption: "Cámara de fermentación" },
      { alt: "Cajas de regalo de Tsuburano en negro y blanco", caption: "" },
    ],
    strengthKicker: "Quality",
    strengthH2: "Cómo producimos",
    strengths: [
      {
        t: "Del concepto a la producción",
        d: "Diseñamos, desarrollamos y elaboramos su producto original íntegramente en nuestro obrador.",
      },
      { t: "Desde lotes pequeños", d: "Desarrollamos y elaboramos productos originales desde lotes pequeños." },
      {
        t: "De lo horneado a lo fresco",
        d: "Nuestro chef pastelero, formado en reconocidas pastelerías, elabora desde dulces horneados hasta delicados dulces frescos.",
      },
      {
        t: "Control higiénico riguroso",
        d: "Desde la elección de los ingredientes hasta cada paso de la elaboración, trabajamos bajo un control estricto.",
      },
    ],
    destKicker: "Partners",
    destH2: "A quién servimos",
    destBody: "Empezando por JR Kyoto Isetan, llevamos dulces originales a clientes como los siguientes.",
    destinations: ["Grandes almacenes", "Hoteles", "Clase business de aerolíneas", "Supermercados"],
    destAlt: "Caja de regalo con seis dulces de distintos dibujos",
    contactKicker: "Contact",
    contactH2: "Hablemos de su producción",
    contactForm: "Escribir desde el formulario",
    contactHome: "Volver al inicio de Ryokuhoen",
  },
};
