// 日本語が原文。他言語はこの型に合わせる（lib/dict/en.ts ほか）。
export const ja = {
  meta: {
    title: "株式会社 緑歩園 | 京都・東山 飲食店運営／スイーツ製造・販売",
    titleShort: "株式会社 緑歩園",
    titleTemplate: "%s | 株式会社 緑歩園",
    description:
      "京都・東山、八坂の塔のふもとに本店を構える株式会社 緑歩園。飲食店運営、自社工房でのスイーツ製造・卸、オンラインストアを通じて、京都の食を届けています。",
    ogAlt: "夜桜と八坂の塔（京都・東山）",
    factoryTitle: "Tsuburano Sweets Factory",
    factoryDescription:
      "株式会社 緑歩園の自社工房 Tsuburano Sweets Factory。貴社オリジナル菓子の企画・開発・製造、小ロットからのOEMを承ります。",
  },
  nav: {
    business: "事業",
    factory: "自社工房",
    company: "会社",
    contact: "お問い合わせ",
    menu: "Menu",
    close: "Close",
    home: "トップへ",
    language: "言語",
    skip: "本文へ移動",
    newTab: "（新しいタブで開きます）",
  },
  hero: {
    ariaLabel: "京都・東山から",
    kicker: "KYOTO / FOOD CULTURE",
    display: ["京の食を、", "しつらえ、ひらき、", "届ける。"],
    ctaBusiness: "事業を見る",
    ctaContact: "お問い合わせ",
    scroll: "Scroll",
    scenes: [
      { alt: "夜桜越しに見る八坂の塔（京都・東山）", kicker: "Higashiyama" },
      {
        alt: "暖簾のかかる入口と苔の庭、飛び石",
        kicker: "Entrance",
        title: ["暖簾をくぐり、", "裏庭へ。"],
        caption: "清水の参道から、一歩内へ。",
      },
      {
        alt: "木の軒ともみじの若葉を見上げる",
        kicker: "Seasons",
        title: ["木の軒に、", "季節の色。"],
        caption: "建物と庭が、季節を映す。",
      },
      {
        alt: "朱の器に盛られた八寸の料理",
        kicker: "Hassun",
        title: ["季節を、", "ひと皿に。"],
        caption: "器に季節を映す、八寸。",
      },
    ],
  },
  policy: {
    kicker: "Our Policy",
    h2: ["京都発、", "食文化の発信。"],
    body:
      "京都・東山、八坂の塔のふもと。築100年の数寄屋造りの建物が、当社の本店〈京都つぶら乃本店〉です。ここを拠点に、伝統の味に新しい価値を加えるため、五条に自家焙煎のカフェを、関西空港の近くにスイーツの製造と卸を手がける自社工房を構えています。",
    alt: "八坂の塔へ続く坂道と、つぶら乃京都本店の外観",
    caption: "東山・八坂の塔へ続く坂道　つぶら乃京都本店",
  },
  sweets: {
    index: "Business",
    kicker: "Sweets",
    h2: "スイーツ製造・販売",
    lead: ["素材を生かし、", "丁寧に焼き上げる。"],
    body:
      "有名洋菓子店で修業を積んだシェフパティシエを迎え、焼き菓子から繊細な生菓子までを自社工房でつくっています。JR京都伊勢丹をはじめ、百貨店やスーパーなど幅広いお客様へオリジナルのお菓子をお届けし、小ロットからのOEM・商品開発も承ります。",
    cta: "自社工房を見る",
    alt: "つぶら乃のどら焼き。抹茶とショコラの生地で、わらび餅とクリームをはさんだ断面。スレートの上に茶葉が散る",
    caption: ["つぶら乃のどら焼き", "抹茶とショコラ、", "わらび餅とクリームをはさんで"],
    insetAlt: "自社工房のデッキオーブン",
    insetCaption: "自社工房　デッキオーブン",
  },
  stores: {
    index: "Business",
    kicker: "Stores",
    h2: "店舗運営",
    intro:
      "京都・東山のお食事処・甘味処〈つぶら乃京都本店〉、新宿御苑内の〈つぶら乃新宿御苑店〉、自社焙煎の珈琲とスイーツの〈馬町珈琲〉。京都を散策の際は、ぜひお立ち寄りください。",
    items: [
      {
        name: "つぶら乃 京都本店",
        desc: "お食事処・甘味処",
        addr: "京都市東山区八坂上町368-1-8",
        alt: "つぶら乃の幕の内弁当。だし巻き、焼き物、炊き合わせなど",
      },
      {
        name: "つぶら乃 新宿御苑店",
        desc: "2022年3月 開店",
        addr: "東京都新宿区内藤町11（新宿御苑内）",
        alt: "つぶら乃新宿御苑店の店内。木のカウンターと白い暖簾",
      },
      {
        name: "馬町珈琲",
        desc: "自社焙煎の珈琲とスイーツ",
        addr: "",
        alt: "馬町珈琲の外観。赤い柱と UMAMACHI COFFEE の看板",
      },
    ],
  },
  shop: {
    index: "Business",
    kicker: "Online Store",
    h2: "オンラインストア",
    lead: ["工房から、", "ご家庭の食卓へ。"],
    body:
      "自社工房から直送する〈つぶら乃〉のお菓子をお届けしています。世界各地から選んだフェアトレードの生豆を、GIESEN社製の焙煎機でじっくり焙煎したオリジナルブレンドのコーヒー豆もご用意しています。",
    alt: "つぶら乃「京都ヴォヤージュ」の焼き菓子。白い皿に色とりどりのクッキーやマカロンが並ぶ",
    caption: "つぶら乃「京都ヴォヤージュ」の焼き菓子",
  },
  company: {
    kicker: "Company",
    h2: "会社概要",
    nameLabel: "商号",
    capitalLabel: "資本金",
    capitalValue: "1000万円",
    trustTitle: "事業領域",
    areas: [
      "飲食店運営",
      "JR京都伊勢丹 だし巻きサンド卸",
      "航空会社ビジネスクラス向けスイーツ卸",
      "百貨店・ホテル OEM",
      "宇治契約農園 お茶卸",
      "自社焙煎コーヒー豆卸",
    ],
    alt: "黒い器の抹茶と、和紙に添えた二色の菓子",
  },
  contact: {
    kicker: "Contact",
    h2: "お問い合わせ",
    body:
      "お取引、OEM・商品開発のご相談、店舗についてのお問い合わせは、こちらからお寄せください。",
    addressLabel: "所在地",
    telLabel: "電話",
    emailLabel: "メール",
    addressLines: ["京都府京都市東山区", "八坂上町368-1"],
    form: {
      name: "お名前",
      email: "メールアドレス",
      message: "お問い合わせ内容",
      submit: "送信する",
      sending: "送信中…",
      note: "フォームは現在準備中です。送信ボタンを押すと、メールでのお問い合わせをご案内します。",
      done: "お問い合わせを受け付けました。内容を確認のうえ、担当者よりご連絡いたします。",
      failed: "送信できませんでした。お手数ですが、メールにてお送りください。",
      preparing: "フォームからの送信は準備中です。お手数ですが、メールにてお送りください。",
      mailLink: "入力内容をメールで送る",
      mailSubject: "【ホームページより】お問い合わせ",
      mailName: "お名前",
      mailEmail: "メール",
    },
  },
  footer: {
    siteLabel: "Site",
    brandsLabel: "Brands",
    policy: "理念",
    business: "事業",
  },
  factory: {
    kicker: "緑歩園の自社工房",
    title: ["Tsuburano", "Sweets Factory"],
    lead: ["関西空港の近く、", "株式会社 緑歩園の自社工房です。"],
    heroAlt: "朱塗りの器にのせた抹茶のテリーヌと栗のテリーヌ、化粧箱",
    introKicker: "Original Sweets",
    introH2: ["貴社のオリジナルを、", "企画から製造まで。"],
    introBody:
      "有名洋菓子店出身のシェフパティシエによる、繊細なお菓子をご提供します。貴社オリジナル商品の企画、開発、製造まで一貫して行います。お気軽にご相談ください。",
    galleryLabel: "工房と製品の写真",
    gallery: [
      { alt: "黒い石板に並んだ、色とりどりの絵柄の菓子", caption: "" },
      { alt: "工房のデッキオーブン", caption: "デッキオーブン" },
      { alt: "工房のホイロ（発酵機）", caption: "ホイロ" },
      { alt: "つぶら乃の化粧箱（黒と白）", caption: "" },
    ],
    strengthKicker: "Quality",
    strengthH2: "製造の強み",
    strengths: [
      { t: "企画から製造まで一貫", d: "貴社オリジナル商品の企画・開発・製造を、自社工房で一貫して行います。" },
      { t: "小ロットから", d: "小ロットからのオリジナル商品の開発・製造を承ります。" },
      {
        t: "焼き菓子から生菓子まで",
        d: "有名洋菓子店出身のシェフパティシエが、焼き菓子から繊細な生菓子までを手がけます。",
      },
      { t: "徹底した衛生管理体制", d: "素材選びから製造工程まで、徹底した管理体制のもとで製造しています。" },
    ],
    destKicker: "Partners",
    destH2: "主な提供先",
    destBody: "JR京都伊勢丹をはじめ、次のようなお客様へオリジナルのお菓子をお届けしています。",
    destinations: ["百貨店", "ホテル", "航空会社 ビジネスクラス", "スーパー"],
    destAlt: "化粧箱と、六種の絵柄の菓子",
    contactKicker: "Contact",
    contactH2: "製造のご相談",
    contactForm: "フォームでお問い合わせ",
    contactHome: "緑歩園トップへ戻る",
  },
};

export type Dict = typeof ja;
