import type { Dict } from "@/lib/dict/ja";

export const ko: Dict = {
  meta: {
    title: "주식회사 료쿠호엔 | 교토 히가시야마 음식점 운영·과자 제조 판매",
    titleShort: "주식회사 료쿠호엔",
    titleTemplate: "%s | 주식회사 료쿠호엔",
    description:
      "주식회사 료쿠호엔은 교토 히가시야마, 야사카 탑 기슭에 본점을 두고 있습니다. 음식점 운영과 자사 공방에서의 과자 제조·도매, 온라인 스토어를 통해 교토의 음식을 전합니다.",
    ogAlt: "밤 벚꽃 너머로 보이는 야사카 탑(교토 히가시야마)",
    factoryTitle: "Tsuburano Sweets Factory",
    factoryDescription:
      "주식회사 료쿠호엔의 자사 공방 Tsuburano Sweets Factory. 귀사 오리지널 과자의 기획·개발·제조와 소량 로트부터의 OEM을 맡고 있습니다.",
  },
  nav: {
    business: "사업",
    factory: "자사 공방",
    company: "회사 소개",
    contact: "문의",
    menu: "Menu",
    close: "Close",
    home: "홈",
    language: "언어",
    skip: "본문으로 건너뛰기",
    newTab: "(새 탭에서 열립니다)",
  },
  hero: {
    ariaLabel: "교토 히가시야마에서",
    kicker: "KYOTO / FOOD CULTURE",
    display: ["교토의 음식을,", "정성껏 차리고, 열고,", "전합니다."],
    ctaBusiness: "사업 보기",
    ctaContact: "문의하기",
    scroll: "Scroll",
    scenes: [
      { alt: "밤 벚꽃 너머로 보이는 야사카 탑(교토 히가시야마)", kicker: "Higashiyama" },
      {
        alt: "노렌이 걸린 입구와 이끼 정원, 징검돌",
        kicker: "Entrance",
        title: ["노렌을 지나,", "안뜰로."],
        caption: "기요미즈 참배길에서 한 걸음 안으로.",
      },
      {
        alt: "나무 처마와 단풍 새잎을 올려다본 모습",
        kicker: "Seasons",
        title: ["나무 처마에,", "계절의 빛깔."],
        caption: "건물과 정원이 계절을 비춥니다.",
      },
      {
        alt: "주칠 그릇에 담긴 핫순 요리",
        kicker: "Hassun",
        title: ["계절을,", "한 접시에."],
        caption: "그릇에 계절을 담는 핫순.",
      },
    ],
  },
  policy: {
    kicker: "Our Policy",
    h2: ["교토에서,", "음식 문화를 전합니다."],
    body:
      "교토 히가시야마, 야사카 탑 기슭. 지은 지 100년 된 스키야 양식의 건물이 저희 본점 〈교토 쓰부라노 본점〉입니다. 이곳을 거점으로 전통의 맛에 새로운 가치를 더하고자, 고조에 자가 배전 카페를, 간사이공항 근처에 과자 제조와 도매를 맡는 자사 공방을 두고 있습니다.",
    alt: "야사카 탑으로 이어지는 언덕길과 쓰부라노 교토 본점 외관",
    caption: "히가시야마, 야사카 탑으로 이어지는 언덕길 — 쓰부라노 교토 본점",
  },
  sweets: {
    index: "Business",
    kicker: "Sweets",
    h2: "과자 제조·판매",
    lead: ["재료를 살려,", "정성껏 구워냅니다."],
    body:
      "유명 양과자점에서 수련한 셰프 파티시에를 맞이해, 구움과자부터 섬세한 생과자까지 자사 공방에서 만들고 있습니다. JR교토 이세탄을 비롯한 백화점과 슈퍼마켓 등 폭넓은 거래처에 오리지널 과자를 공급하며, 소량 로트부터의 OEM·상품 개발도 맡고 있습니다.",
    cta: "자사 공방 보기",
    alt: "쓰부라노 도라야키. 말차와 초콜릿 반죽에 와라비모치와 크림을 넣은 단면, 슬레이트 위에 찻잎",
    caption: ["쓰부라노의 도라야키", "말차와 초콜릿,", "와라비모치와 크림을 넣어"],
    insetAlt: "자사 공방의 데크 오븐",
    insetCaption: "자사 공방 — 데크 오븐",
  },
  stores: {
    index: "Business",
    kicker: "Stores",
    h2: "매장 운영",
    intro:
      "교토 히가시야마의 식사·디저트 가게 〈쓰부라노 교토 본점〉, 도쿄 신주쿠 교엔 안의 〈쓰부라노 신주쿠 교엔점〉, 자가 배전 커피와 디저트의 〈우마마치 커피〉. 교토를 거닐 때 들러 주세요.",
    items: [
      {
        name: "쓰부라노 교토 본점",
        desc: "식사·디저트",
        addr: "교토시 히가시야마구 야사카카미마치 368-1-8",
        alt: "쓰부라노의 마쿠노우치 도시락. 다시마키 계란, 구이, 조림 등",
      },
      {
        name: "쓰부라노 신주쿠 교엔점",
        desc: "2022년 3월 오픈",
        addr: "도쿄도 신주쿠구 나이토마치 11 (신주쿠 교엔 내)",
        alt: "쓰부라노 신주쿠 교엔점 내부. 나무 카운터와 흰 노렌",
      },
      {
        name: "우마마치 커피",
        desc: "자가 배전 커피와 디저트",
        addr: "",
        alt: "우마마치 커피 외관. 붉은 기둥과 UMAMACHI COFFEE 간판",
      },
    ],
  },
  shop: {
    index: "Business",
    kicker: "Online Store",
    h2: "온라인 스토어",
    lead: ["공방에서,", "가정의 식탁으로."],
    body:
      "자사 공방에서 직접 보내는 〈쓰부라노〉의 과자를 전해 드립니다. 세계 각지에서 고른 공정무역 생두를 GIESEN 로스터로 천천히 볶은 오리지널 블렌드 원두도 준비되어 있습니다.",
    alt: "쓰부라노 ‘교토 보야주’ 구움과자. 흰 접시에 색색의 쿠키와 작은 과자가 놓여 있다",
    caption: "쓰부라노 ‘교토 보야주’ 구움과자",
  },
  company: {
    kicker: "Company",
    h2: "회사 소개",
    nameLabel: "상호",
    capitalLabel: "자본금",
    capitalValue: "1,000만 엔",
    trustTitle: "사업 영역",
    areas: [
      "음식점 운영",
      "JR교토 이세탄 다시마키 샌드 도매",
      "항공사 비즈니스 클래스용 디저트 도매",
      "백화점·호텔 OEM",
      "우지 계약 농원 차 도매",
      "자가 배전 커피 원두 도매",
    ],
    alt: "검은 그릇의 말차와 화지 위에 놓인 두 가지 과자",
  },
  contact: {
    kicker: "Contact",
    h2: "문의",
    body: "거래, OEM·상품 개발 상담, 매장에 관한 문의는 이곳으로 보내 주세요.",
    addressLabel: "주소",
    telLabel: "전화",
    emailLabel: "이메일",
    addressLines: ["일본 교토부 교토시 히가시야마구", "야사카카미마치 368-1 (우편번호 605-0827)"],
    form: {
      name: "성함",
      email: "이메일 주소",
      message: "문의 내용",
      submit: "보내기",
      sending: "보내는 중…",
      note: "문의 폼은 현재 준비 중입니다. 보내기를 누르면 이메일 작성 화면을 안내합니다.",
      done: "문의를 접수했습니다. 내용을 확인한 뒤 담당자가 연락드리겠습니다.",
      failed: "보내지 못했습니다. 번거로우시겠지만 이메일로 보내 주세요.",
      preparing: "폼 전송은 준비 중입니다. 번거로우시겠지만 이메일로 보내 주세요.",
      mailLink: "입력한 내용을 이메일로 보내기",
      mailSubject: "[홈페이지] 문의",
      mailName: "성함",
      mailEmail: "이메일",
    },
  },
  footer: {
    siteLabel: "Site",
    brandsLabel: "Brands",
    policy: "이념",
    business: "사업",
  },
  factory: {
    kicker: "료쿠호엔의 자사 공방",
    title: ["Tsuburano", "Sweets Factory"],
    lead: ["간사이공항 근처에 있는", "주식회사 료쿠호엔의 자사 공방입니다."],
    heroAlt: "주칠 그릇에 올린 말차 테린과 밤 테린, 그리고 선물 상자",
    introKicker: "Original Sweets",
    introH2: ["귀사의 오리지널을,", "기획부터 제조까지."],
    introBody:
      "유명 양과자점 출신의 셰프 파티시에가 섬세한 과자를 만듭니다. 귀사 오리지널 상품의 기획, 개발, 제조까지 일관되게 맡습니다. 편하게 상담해 주세요.",
    galleryLabel: "공방과 제품 사진",
    gallery: [
      { alt: "검은 석판 위에 놓인 색색의 무늬 과자", caption: "" },
      { alt: "공방의 데크 오븐", caption: "데크 오븐" },
      { alt: "공방의 발효기", caption: "발효기" },
      { alt: "쓰부라노의 선물 상자(검정과 흰색)", caption: "" },
    ],
    strengthKicker: "Quality",
    strengthH2: "제조의 강점",
    strengths: [
      { t: "기획부터 제조까지 일관", d: "귀사 오리지널 상품의 기획·개발·제조를 자사 공방에서 일관되게 진행합니다." },
      { t: "소량 로트부터", d: "소량 로트부터 오리지널 상품의 개발과 제조를 맡습니다." },
      {
        t: "구움과자부터 생과자까지",
        d: "유명 양과자점 출신의 셰프 파티시에가 구움과자부터 섬세한 생과자까지 만듭니다.",
      },
      { t: "철저한 위생 관리", d: "재료 선정부터 제조 공정까지 철저한 관리 체제 아래 제조하고 있습니다." },
    ],
    destKicker: "Partners",
    destH2: "주요 공급처",
    destBody: "JR교토 이세탄을 비롯해 다음과 같은 고객에게 오리지널 과자를 공급하고 있습니다.",
    destinations: ["백화점", "호텔", "항공사 비즈니스 클래스", "슈퍼마켓"],
    destAlt: "선물 상자와 여섯 가지 무늬의 과자",
    contactKicker: "Contact",
    contactH2: "제조 상담",
    contactForm: "폼으로 문의하기",
    contactHome: "료쿠호엔 홈으로",
  },
};
