// 繁體中文（台灣・香港向け）
import type { Dict } from "@/lib/dict/ja";

export const zh: Dict = {
  meta: {
    title: "綠步園股份有限公司 | 京都東山 餐飲經營／和洋菓子製造販售",
    titleShort: "綠步園股份有限公司",
    titleTemplate: "%s | 綠步園股份有限公司",
    description:
      "綠步園股份有限公司位於京都東山、八坂塔腳下。透過餐飲經營、自家工坊的菓子製造與批發，以及網路商店，將京都的飲食文化送到您的餐桌。",
    ogAlt: "夜櫻與八坂塔（京都・東山）",
    factoryTitle: "Tsuburano Sweets Factory",
    factoryDescription:
      "Tsuburano Sweets Factory 是綠步園股份有限公司的自家工坊。承接貴公司原創菓子的企劃、開發與製造，小批量亦可代工。",
  },
  nav: {
    business: "事業",
    factory: "自家工坊",
    company: "公司簡介",
    contact: "聯絡我們",
    menu: "Menu",
    close: "Close",
    home: "首頁",
    language: "語言",
    skip: "跳至主要內容",
    newTab: "（於新分頁開啟）",
  },
  hero: {
    ariaLabel: "來自京都東山",
    kicker: "KYOTO / FOOD CULTURE",
    display: ["京都的飲食，", "細心備辦、敞門相迎、", "送到您手中。"],
    ctaBusiness: "查看事業",
    ctaContact: "聯絡我們",
    scroll: "Scroll",
    scenes: [
      { alt: "透過夜櫻望見的八坂塔（京都・東山）", kicker: "Higashiyama" },
      {
        alt: "掛著暖簾的入口與青苔庭園、踏石",
        kicker: "Entrance",
        title: ["穿過暖簾，", "走進後院。"],
        caption: "自清水參道，向內一步。",
      },
      {
        alt: "仰望木造屋簷與新綠的楓葉",
        kicker: "Seasons",
        title: ["木簷之下，", "四季的顏色。"],
        caption: "建築與庭園，映照四季的流轉。",
      },
      {
        alt: "盛於朱漆器皿的八寸料理",
        kicker: "Hassun",
        title: ["把季節，", "盛入一皿。"],
        caption: "八寸——以器皿映照季節。",
      },
    ],
  },
  policy: {
    kicker: "Our Policy",
    h2: ["自京都，", "傳遞飲食文化。"],
    body:
      "京都東山、八坂塔腳下，屋齡百年的數寄屋建築，正是本公司的本店〈京都つぶら乃本店〉。我們以此為據點，為傳統的滋味添上新的價值：在五條設有自家烘焙的咖啡館，並在關西機場附近設置從事菓子製造與批發的自家工坊。",
    alt: "通往八坂塔的坡道與つぶら乃京都本店外觀",
    caption: "東山・通往八坂塔的坡道　つぶら乃京都本店",
  },
  sweets: {
    index: "Business",
    kicker: "Sweets",
    h2: "菓子製造・販售",
    lead: ["發揮素材本味，", "細心烘焙。"],
    body:
      "我們延請曾於知名西點名店修業的主廚甜點師，於自家工坊製作從烘焙點心到細緻生菓子的各式商品。除了供應JR京都伊勢丹等百貨公司與超市的原創菓子，也承接小批量起的代工製造與商品開發。",
    cta: "參觀自家工坊",
    alt: "つぶら乃銅鑼燒。抹茶與巧克力餅皮，夾入蕨餅與鮮奶油的剖面，石板上散落茶葉",
    caption: ["つぶら乃的銅鑼燒", "抹茶與巧克力，", "夾入蕨餅與鮮奶油"],
    insetAlt: "自家工坊的層爐",
    insetCaption: "自家工坊　層爐",
  },
  stores: {
    index: "Business",
    kicker: "Stores",
    h2: "門市經營",
    intro:
      "京都東山的餐飲與甜點店〈つぶら乃京都本店〉、位於東京新宿御苑內的〈つぶら乃新宿御苑店〉，以及提供自家烘焙咖啡與甜點的〈馬町珈琲〉。到京都散步時，歡迎順道前來。",
    items: [
      {
        name: "つぶら乃 京都本店",
        desc: "餐飲・甜點",
        addr: "京都市東山區八坂上町368-1-8",
        alt: "つぶら乃的幕之內便當。高湯蛋卷、燒物、燉煮菜等",
      },
      {
        name: "つぶら乃 新宿御苑店",
        desc: "2022年3月 開幕",
        addr: "東京都新宿區內藤町11（新宿御苑內）",
        alt: "つぶら乃新宿御苑店店內。木質吧檯與白色暖簾",
      },
      {
        name: "馬町珈琲",
        desc: "自家烘焙咖啡與甜點",
        addr: "",
        alt: "馬町珈琲外觀。紅色柱子與 UMAMACHI COFFEE 招牌",
      },
    ],
  },
  shop: {
    index: "Business",
    kicker: "Online Store",
    h2: "網路商店",
    lead: ["從工坊，", "直送您的餐桌。"],
    body:
      "自家工坊直送的〈つぶら乃〉菓子，歡迎選購。我們也備有以GIESEN烘豆機慢火烘焙、選自世界各地公平貿易生豆的原創配方咖啡豆。",
    alt: "つぶら乃「京都Voyage」烘焙點心。白盤上排列著色彩繽紛的餅乾與小點",
    caption: "つぶら乃「京都Voyage」烘焙點心",
  },
  company: {
    kicker: "Company",
    h2: "公司簡介",
    nameLabel: "公司名稱",
    capitalLabel: "資本額",
    trustTitle: "事業領域",
    areas: [
      "餐飲店經營",
      "JR京都伊勢丹 高湯蛋卷三明治批發",
      "航空公司商務艙用菓子批發",
      "百貨公司・飯店代工製造",
      "宇治契作茶園 茶葉批發",
      "自家烘焙咖啡豆批發",
    ],
    alt: "黑色茶碗中的抹茶，與和紙上的兩色菓子",
  },
  contact: {
    kicker: "Contact",
    h2: "聯絡我們",
    body: "業務往來、代工製造與商品開發的洽詢，或門市相關問題，歡迎由此與我們聯繫。",
    addressLabel: "地址",
    telLabel: "電話",
    emailLabel: "電子郵件",
    addressLines: ["日本京都府京都市東山區", "八坂上町368-1（郵遞區號 605-0827）"],
    form: {
      name: "姓名",
      email: "電子郵件",
      message: "洽詢內容",
      submit: "送出",
      sending: "傳送中…",
      note: "表單目前準備中。按下送出後，將引導您以電子郵件聯繫。",
      done: "已收到您的訊息。我們確認內容後會盡快與您聯繫。",
      failed: "訊息未能送出，敬請改以電子郵件與我們聯繫。",
      preparing: "表單目前準備中，敬請改以電子郵件與我們聯繫。",
      mailLink: "以電子郵件寄出填寫的內容",
      mailSubject: "【網站來信】洽詢",
      mailName: "姓名",
      mailEmail: "電子郵件",
    },
  },
  footer: {
    siteLabel: "Site",
    brandsLabel: "Brands",
    policy: "理念",
    business: "事業",
  },
  factory: {
    kicker: "綠步園的自家工坊",
    title: ["Tsuburano", "Sweets Factory"],
    lead: ["位於關西機場附近，", "綠步園股份有限公司的自家工坊。"],
    heroAlt: "朱漆器皿上的抹茶與栗子生乳酪條，以及禮盒",
    introKicker: "Original Sweets",
    introH2: ["貴公司的原創商品，", "從企劃到製造。"],
    introBody:
      "由出身知名西點名店的主廚甜點師，為您製作細緻的菓子。從貴公司原創商品的企劃、開發到製造，皆由本公司一貫負責。歡迎隨時洽詢。",
    galleryLabel: "工坊與產品的照片",
    gallery: [
      { alt: "黑色石板上排列著色彩繽紛的圖案菓子", caption: "" },
      { alt: "工坊的層爐", caption: "層爐" },
      { alt: "工坊的發酵箱", caption: "發酵箱" },
      { alt: "つぶら乃的禮盒（黑與白）", caption: "" },
    ],
    strengthKicker: "Quality",
    strengthH2: "製造實力",
    strengths: [
      { t: "從企劃到製造一貫作業", d: "貴公司原創商品的企劃、開發與製造，皆於自家工坊一貫完成。" },
      { t: "小批量起接單", d: "自小批量起承接原創商品的開發與製造。" },
      {
        t: "從烘焙點心到生菓子",
        d: "出身知名西點名店的主廚甜點師，從烘焙點心到細緻的生菓子皆可製作。",
      },
      { t: "徹底的衛生管理", d: "從素材選擇到製造流程，皆在嚴格的管理體制下進行。" },
    ],
    destKicker: "Partners",
    destH2: "主要供應對象",
    destBody: "以JR京都伊勢丹為首，我們為以下客戶提供原創菓子。",
    destinations: ["百貨公司", "飯店", "航空公司商務艙", "超市"],
    destAlt: "禮盒與六種圖案的菓子",
    contactKicker: "Contact",
    contactH2: "製造洽詢",
    contactForm: "以表單洽詢",
    contactHome: "返回綠步園首頁",
  },
};
